# fly.toml app configuration file generated for seschedule on 2023-12-24T14:18:55-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "seschedule"
primary_region = "gru"
kill_signal = "SIGTERM"

[build]

[env]
  DATABASE_PATH = "/tmp/seschedule.db"
  PHX_HOST = "seschedule.fly.dev"
  PORT = "8443"

[http_service]
  internal_port = 8443
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000