categories = [
  all: "Todas",
  "artes-visuais": "artes visuais",
  "cinema-e-video": "cinema e vídeo",
  musica: "música",
  "musica-show": "shows de música",
  danca: "dança",
  teatro: "teatro",
  "acoes-para-cidadania": "ações para cidadania",
  alimentacao: "alimentação",
  circo: "circo",
  criancas: "crianças",
  empresas: "empresas",
  "esportes-e-atividade-fisica": "esporte e atividade física",
  "gestao-cultural": "gestão cultural",
  idosos: "Idosos",
  intergeracoes: "Intergerações",
  jovens: "Jovens",
  literatura: "literatura",
  "meio-ambiente": "meio ambiente",
  multilinguagem: "Multilinguagem",
  saude: "saúde",
  "tecnologias-e-artes": "tecnologias e artes",
  turismo: "turismo"
]
