places = [
  all: "Todas",
  "25": "Araraquara",
  "26": "Bauru",
  "27": "Bertioga",
  "28": "Birigui",
  "29": "Campinas",
  "30": "Catanduva",
  "31": "Jundiaí",
  "32": "Piracicaba",
  "33": "Presidente Prudente",
  "34": "Registro",
  "35": "Ribeirão Preto",
  "36": "Rio Preto",
  "37": "Santos",
  "42": "São Carlos",
  "40": "São José dos Campos",
  "38": "Sorocaba",
  "41": "Taubaté",
  "761": "14 Bis",
  "2": "24 de Maio",
  "43": "Avenida Paulista",
  "47": "Belenzinho",
  "48": "Bom Retiro",
  "49": "Campo Limpo",
  "50": "Carmo",
  "730": "Casa Verde",
  "51": "Centro de Pesquisa e Formação",
  "52": "CineSesc",
  "53": "Consolação",
  "54": "Florêncio de Abreu",
  "71": "Guarulhos",
  "55": "Interlagos",
  "56": "Ipiranga",
  "57": "Itaquera",
  "80": "Mogi das Cruzes",
  "58": "Osasco",
  "59": "Parque Dom Pedro II",
  "60": "Pinheiros",
  "61": "Pompeia",
  "62": "Santana",
  "63": "Santo Amaro",
  "64": "Santo André",
  "65": "São Caetano",
  "66": "Vila Mariana"
]
